apiVersion: v1
kind: ConfigMap
metadata:
  name: ib-devices
  namespace: kube-system
data:
  config.json: |
    {
      "resourceName": "sm.com/ib",
      "socketName": "sm-ib.sock",
      "numDevices": 1000,
      "hostDevices": [{
        "hostPath": "/dev/infiniband/uverbs0",
        "containerPath": "/dev/infiniband/uverbs0",
        "permission": "rwm"
      },
      {
        "hostPath": "/dev/infiniband/uverbs1" ,
        "containerPath": "/dev/infiniband/uverbs1",
        "permission": "rwm"
      },
      {
        "hostPath": "/dev/infiniband/uverbs2" ,
        "containerPath": "/dev/infiniband/uverbs2",
        "permission": "rwm"
      },
      {
        "hostPath": "/dev/infiniband/uverbs3" ,
        "containerPath": "/dev/infiniband/uverbs3",
        "permission": "rwm"
      },
      {
        "hostPath": "/dev/infiniband/rdma_cm",
        "containerPath": "/dev/infiniband/rdma_cm",
        "permission": "rwm"
      }]
    }