apiVersion: v1
kind: Pod
metadata:
  name: ib-test
spec:
  restartPolicy: OnFailure
  containers:
  - image: alpine
    name: ib-test-ctr
    resources:
      limits:
        github.com/everpeace-ib: 1
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband
      sleep 1000000
